### PR TITLE
Update styles for primary action button

### PR DESCRIPTION
**Pull request by donokuda**
Ref: https://github.com/github/VisualStudio/issues/356#issuecomment-226739689

> On a different note, I've been doing the PR creation and I'm finding the green button pretty hard to read. The white on flat green just disappears. It's also almost impossible to tell when it's enabled/disabled, too :/

This PR updates the color for the primary action button to match the green specified in [primer](http://primercss.io/colors/).

The text is also bolded for better readability / contrast.

EDIT: This only updates the color for the light and blue themes. The dark theme is unaffected aside from bolding the text.

screen shot 2016-06-20 at 11 48 28 am

cc: @shana

### CODE REVIEW

**Comment by shana** [comment]
Aah, awesome! Do we also have a style for disabled buttons?

**Comment by donokuda** [comment]
>  Do we also have a style for disabled buttons?

I thought we did but it turns out we didn't! (or at least it wasn't getting set)

Added in ac0edec

image

**Comment by shana** [comment]
The disabled style doesn't make it obvious at all that it's a disabled button... If you've never seen the button in its enabled state, it just looks like just a faded style. This kinda works in the website because the website 1) always has the buttons enabled from the start 2) they have a faux-3d style that becomes flat when they get disabled (which kinda works as a hint... kinda)

I feel like green should only be there to signal that everything is green and ready to go. How about a monochromatic style for disabled buttons?

**Comment by donokuda** [comment]
> Looking at the Commit button in the Changes pane, where there are no other buttons in the area and the Commit button starts disabled - the Light and the Dark theme make the background of the button the same as the background of the window, so only the outline and the gray text is showing. The blue theme turns the button background gray but the window background is white.

That makes sense. What if we treated our primary button the same: appear like a normal disabled button? I also took note of how the blue theme looks like a faded style and tried to make our disabled button's background closer to the window background color:

artboard 20

(I purposefully removed the "Cancel" button so we have a better sense if it works as a disabled button)

And then when enabled, we give it the full green button style:

button-enabled

> BTW, all the themes highlight enabled buttons on mouse hover (but that's learned behaviour, albeit pretty standard on windows). We should probably make use of that as an extra hint of state.

💯 Having a hover state will help out with understanding if a button is disabled or not:

primary-button-disabled

primary-button

By the way, these changes are only on the blue theme. If they look good, then we can go ahead and work the changes to the other themes.

**Comment by shana** [comment]
I've added the missing color definitions on the dark and light themes so that we can pull this in now. The colors are likely not correct and require validation, let's open another PR for that.

**Comment by shana** [comment]
This fixes #356

**Pull request merged**
