### PR TITLE
Merge master to feature/gist-support

### PR DESCRIPTION
**Pull request by grokys**
This PR merges the latest changes on master into feature/gist-support

### CODE REVIEW

**Comment by shana** [comment]
Did you have any conflicts that you had to resolve?

**Comment by grokys** [comment]
Yeah, a fair few.

**Comment by shana** [comment]
Which ones? There's no point in reviewing a merge PR unless I know which files conflicted... :smile:

**Comment by shana** [comment]
Actually, there's no real value in making this a PR, it's master to non-master and the PR diff is useless anyway.

**Pull request merged**
