### PR TITLE
[WIP] Generate Copy/Open link based on the latest commit

### LINKED ISSUE #343: Link generation for Open/Link to GitHub should use the latest commit of the current file
The "Open on GitHub" feature always seems to try to open the file on master - if I'm on a branch that file might not exist or be completely different. It would be good to open the file on the correct branch on the site.

### PR DESCRIPTION
**Pull request by paladique**
Fixes #343

### CODE REVIEW

**Comment by shana** [comment]
Probably worth checking whether the branch is tracking a remote branch and whether the commit hashes match there, and then maybe checking if any commits are reachable on that tracking branch, as an optimization, before going on enumerating all the remotes branches and all the local commits. Very likely the branch has been pushed at least once so that might hit a large chunk of use cases.

**Comment by paladique** [comment]
@shana so I want to test this new method `GetLatestPushedSha` (GitServiceTests seemed fitting), and I think I need to mock a directory like in `SimpleRepositoryModelTests`, but the base classes between the two are different so I can't create a local directory with a `TempBaseClass`.

Didn't push this yet, but if I swap `TempBaseClass`  for `TempFileBaseClass` in `GitServiceTests` it didn't seem to break anything so I'm wondering if to get access to methods like `Directory.CreateSubdirectory` is a fair reason to switch the base class.

**Comment by paladique** [comment]
I realize I might need to make a new PR with the merged refactor in master, but wanna get through this test before I do that

**Comment by shana** [comment]
> Didn't push this yet, but if I swap TempBaseClass for TempFileBaseClass in GitServiceTests it didn't seem to break anything so I'm wondering if switching the base class is fair reason to get access to methods like Directory.CreateSubdirectory

The TempFileBaseClass has some... issues. It's kinda fundamentally flawed,  https://github.com/github/VisualStudio/pull/544 takes a different approach on that. It's probably best to close this PR and leave it be as-is, create a new branch from master, port your changes over to it, to start with. Then it'll be easier to write tests using temp dirs. If you port over this PR to master within the next three hours, I'll still be around to review it!

**Pull request closed without merging**
