### PR TITLE
 Fixes Bug - GitHub section of Home page is cut when large font is used

### PR DESCRIPTION
**Pull request by gitexperience**
Bug link :- https://github.com/github/VisualStudio/issues/159 
This PR provides a ScrollViewer (hidden) so that all of the content can be seen just by scrolling. This is useful when the size of the font is increased large enough to fit the complete text inside StackPanel.

### CODE REVIEW

**Comment by shana** [comment]
The panel should make the section grow so it doesn't require any scrolling no matter how big it gets. Scrolling is not an appropriate solution here, not unless there's no other way of getting the content visible.

**Comment by shana** [comment]
@gitexperience Are you working on addressing the comment I left above? If not, I'm closing this PR, as it doesn't fix the issue correctly.

**Comment by gitexperience** [comment]
@shana , if possible, please keep it open for a while, I am currently working on my GSoC proposal so unable to work in this right now , will try to solve this and address you once i am done with my proposal.

**Comment by shana** [comment]
@gitexperience Sure!

**Comment by gitexperience** [comment]
It will now look like this

**Comment by shana** [comment]
@gitexperience Thanks for the fix! Your patch will be merged as part of #264

**Pull request closed without merging**
