### PR TITLE
Make NCrunch happy

### PR DESCRIPTION
**Pull request by jcansdale**
We now have the *possibility* of seeing green when executing tests with NCrunch. 😉 

image

- Explicitly handle `TaskCanceledException` thrown by `ReturnsCheckingWhenProbeNotFinished`
- Remove Serilog and GitHub.Extensions dependencies from *DictionaryManager code
  - This lets tests executed by NCrunch in new app domain pass

### CODE REVIEW

**Comment by grokys** [comment]
Hmm, I'm still getting errors:

## ReturnsInvalidWhenProbeReturnsFailed
```
An exception was thrown in the Task Environment: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitHub.ViewModels.Dialog.LoginToGitHubForEnterpriseViewModel.<EnterpriseUrlChanged>d__26.MoveNext() in D:\projects\github\VisualStudio\src\GitHub.App\ViewModels\Dialog\LoginToGitHubForEnterpriseViewModel.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitHub.ViewModels.Dialog.LoginToGitHubForEnterpriseViewModel.<EnterpriseUrlChanged>d__26.MoveNext() in D:\projects\github\VisualStudio\src\GitHub.App\ViewModels\Dialog\LoginToGitHubForEnterpriseViewModel.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

# PullRequestServiceTests

```
System.TypeInitializationException : The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
  ----> System.DllNotFoundException : Unable to load DLL 'git2-a5cf255': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_repository_init_ext(git_repository*& repository, FilePath path, GitRepositoryInitOptions options)
   at LibGit2Sharp.Core.Proxy.git_repository_init_ext(FilePath workdirPath, FilePath gitdirPath, Boolean isBare) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\Proxy.cs:line 2477
   at LibGit2Sharp.Repository.Init(String path, Boolean isBare) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Repository.cs:line 454
   at LibGit2Sharp.Repository.Init(String path) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Repository.cs:line 443
   at PullRequestServiceTests.CreateRepository(TempDirectory tempDirectory) in D:\projects\github\VisualStudio\test\GitHub.App.UnitTests\Services\PullRequestServiceTests.cs:line 564
   at PullRequestServiceTests.TheCountSubmodulesToSyncMethod.<AddedFile_False_Async>d__7.MoveNext() in D:\projects\github\VisualStudio\test\GitHub.App.UnitTests\Services\PullRequestServiceTests.cs:line 408
   --- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
   --DllNotFoundException
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor() in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\NativeMethods.cs:line 35
   at LibGit2Sharp.Core.NativeMethods..cctor() in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\NativeMethods.cs:line 81
```

## FilterTitleRun2

```
Test cancelled by user
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)
   at NUnit.Framework.Internal.MethodWrapper.Invoke(Object fixture, Object[] args)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunNonAsyncTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.Execute(TestExecutionContext context)


Timeout of 5000 expired
```

**Comment by jcansdale** [comment]
@grokys do you think this is worth merging?  Is NCRunch at least happier?

**Comment by meaghanlewis** [comment]
@jcansdale all 4 errors are the same:
```
System.Windows.Markup.XamlParseException : 'Set property 'GitHub.VisualStudio.UI.Helpers.ThemeDictionaryManager.Source' threw an exception.' Line number '9' and line position '10'.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at GitHub.LoadingResourceDictionary.set_Source(Uri value) in C:\Users\atom\Source\Repos\VisualStudio\src\GitHub.UI\Helpers\LoadingResourceDictionary.cs:line 20
   at GitHub.UI.Helpers.UnitTests.LoadingResourceDictionaryIntegrationTests.TheSourceProperty.<>c__DisplayClass0_0.<SetInLoadFromContext>b__0() in C:\Users\atom\Source\Repos\VisualStudio\test\GitHub.UI.UnitTests\LoadingResourceDictionaryIntegrationTests.cs:line 24
   at GitHub.UI.Helpers.UnitTests.AppDomainContext.Remote.Invoke(String assemblyFile, String typeName, String methodName, Dictionary`2 fieldValues) in C:\Users\atom\Source\Repos\VisualStudio\test\Helpers\AppDomainContext.cs:line 72
   at GitHub.UI.Helpers.UnitTests.AppDomainContext.Remote.Invoke(String assemblyFile, String typeName, String methodName, Dictionary`2 fieldValues)
   at GitHub.UI.Helpers.UnitTests.AppDomainContext.Invoke(Action remoteAction) in C:\Users\atom\Source\Repos\VisualStudio\test\Helpers\AppDomainContext.cs:line 50
   at GitHub.UI.Helpers.UnitTests.AppDomainContext.Invoke(AppDomainSetup setup, Action remoteAction) in C:\Users\atom\Source\Repos\VisualStudio\test\Helpers\AppDomainContext.cs:line 15
   at GitHub.UI.Helpers.UnitTests.LoadingResourceDictionaryIntegrationTests.TheSourceProperty.SetInLoadFromContext(String url) in C:\Users\atom\Source\Repos\VisualStudio\test\GitHub.UI.UnitTests\LoadingResourceDictionaryIntegrationTests.cs:line 19
   --FileNotFoundException
   at GitHub.VisualStudio.UI.Helpers.ThemeDictionaryManager.InitTheme(Uri themeUri)
   at GitHub.VisualStudio.UI.Helpers.ThemeDictionaryManager.set_Source(Uri value) in C:\Users\atom\Source\Repos\VisualStudio\src\GitHub.VisualStudio.UI\Helpers\ThemeDictionaryManager.cs:line 25
```

I didn't notice before but I'm also getting similar errors with NUnit and 17 failures there:

```
Message: System.IO.FileLoadException : Could not load file or assembly 'Microsoft.VisualStudio.Validation, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by meaghanlewis** [comment]
Adding the package `Microsoft.VisualStudio.Shell.14.0` to **GitHub.UI.UnitTests** fixed my 4 errors. I'm still not sure why I had to do this if you and Steven didn't have to.

Also, after resolving those I see 1 error now (looks like you had the same error in your [previous comment](https://github.com/github/VisualStudio/pull/1765#issuecomment-401923674)):
screen shot 2018-07-03 at 11 22 08 am

**Pull request merged**
