### PR TITLE
Pass progress object to TE clone.

### LINKED ISSUE #800: GitHub provider on Start Page should use the new Clone API
In VS 2017, we've introduced a new Clone API that enables cloning in Team Explorer and returns progress through an IProgress<ServiceProgressData>.

To enable the Start Page to display progress in the status bar, the GitHub provider should pass on the IProgress<ServiceProgressData> to the Clone API.

A sample usage of the new Clone API can be found here:
https://github.com/prasethu/CloneAPISample

Specifically this file: CloneAPISample/VSIXProject2/Command1.cs

### LINKED ISSUE #849: Clone repo while cloning another repo
- GitHub Extension for Visual Studio  version: 2.2.0.6
- Visual Studio version: 14.0.25431.01 Update 3

### Steps:
- Clone an arbitrary repo from your repos on `GitHub-Connect-Team Explorer` 
- Clone another repo while **cloning** the previous one (the connection is soooooo sloooooow in China 😅 )

### Current behavior:
- The extension creates two **folders** for corresponding repos
- The first repo is cloned successfully
- The second repo is **not cloned** (the folder is left empty)
- When trying again to clone the second repo, the extension will say that the folder is already existing **(red _!_)**.

### Expected behavior:
- Disable `clone` link while another one is processing
- Add the pending clone action into a queue

😉 Love this extension so much.

### PR DESCRIPTION
**Pull request by grokys**
In order to fix #800, we need to pass a progress object to `IGitActionsExt.CloneAsync`. This was not easy before as the call to `CloneAsync` was hidden in the Clone button command in RepositoryCloneService. This commit:

- Stops the `RepositoryCloneViewModel` from doing the clone itself
- Adds a `DialogService` to show the clone dialog and return its results
- Adds a "progress" parameter to `RepositoryCloneService.CloneRepository` and `IVSGitServices.Clone`
- Passes the progress object from the start page to `RepositoryCloneService.CloneRepository`

This commit also fixes #849:

- `RepositoryCloneService.CloneRepository` and `IVSGitServices.Clone` now return a task that doesn't complete until the clone is complete
- Changes `GitHubConnectSection` to have a `Clone` command which disabled itself while the clone is in progress.

Also a small rename:

- Renamed `UIControllerFlow.StartPageClone` -> `ReClone`: The old name was misleading: a normal clone can also be initiated from the start page, this flow is for re-cloning a previously cloned repository.

### CODE REVIEW

**Comment by grokys** [comment]
Uhh, not sure what's happened here, a load of changes aren't present!

**Comment by jcansdale** [comment]
Seems to be working now!

Is this the new progress bar?
image

**Comment by jcansdale** [comment]
Unfortunately it hung near the end with the following: 😢 
image

image

Have you been able to clone `GitHub/VisualStudio`?

**Comment by grokys** [comment]
This seems to be a problem with VS2017 - it happens even when you clone from TE directly.

**Comment by jcansdale** [comment]
Clone and re-clone seems to be working. 👍 from me!

**Pull request merged**
