### PR TITLE
Update Styles.xaml

### PR DESCRIPTION
**Pull request by kessanro**
#3da4f4 bit diffrent at line i forgot

### CODE REVIEW

**Comment by shana** [comment]
Hi @kessanro! We appreciate the effort, but don't really see the relevance of this change. Is there something in our blue shade that's bothering you?

**Comment by kessanro** [comment]
kindof it does not match github blue

**Comment by kessanro** [comment]
this is a start im going to try to make it asyer since my laptop was in for repair

**Comment by shana** [comment]
@donokuda Could you double check out shades of blue, see if they match our style in the website and other apps?

**Comment by donokuda** [comment]
I did a search for `GitHubAccentColor` and it looks like we don't use it in our extension at all. This might have been a color imported from GitHub Desktop for Windows.

image

As far as I know, we don't use specify any blue in our extension. If we do, we should strongly consider using the color Visual Studio provides us instead of a custom blue (for controls like a hyperlink.)

**Comment by shana** [comment]
> I did a search for GitHubAccentColor and it looks like we don't use it in our extension at all. This might have been a color imported from GitHub Desktop for Windows.

Oh, haha, fun, dead code! 😄 

> As far as I know, we don't use specify any blue in our extension. If we do, we should strongly consider using the color Visual Studio provides us instead of a custom blue (for controls like a hyperlink.)

The dialogs for login and friends use a custom theme that matches the desktop app but not VS (on purpose). The login/clone/create buttons on those dialogs are blue (have a blue border and animate to blue when hovered upon). I wonder what blue we're using there...

**Comment by donokuda** [comment]
> The dialogs for login and friends use a custom theme that matches the desktop app but not VS (on purpose). The login/clone/create buttons on those dialogs are blue (have a blue border and animate to blue when hovered upon). I wonder what blue we're using there...

D'oh! Forgot about those dialogs.

It looks like we're using two different blues: `#4a88c3` for the blue text and `#49a5ed` for the circle/icon buttons.

**Comment by shana** [comment]
@kessanro So it looks like the color that you changed in this PR is not actually being used, so there's no real point in doing this change. If you have suggestions on how to improve our UI, please open an issue for it, preferably with mockups of what you want to do, so we can have a discussion about that!

**Comment by kessanro** [comment]
ok

**Pull request closed without merging**
