### PR TITLE
Remove copyright year from LICENSE file

### PR DESCRIPTION
**Pull request by Phineas**

### CODE REVIEW

**Comment by Haacked** [comment]
In US copyright law, a copyright notice is not required to be protected under copyright law. Thus this notice is entirely educational. And in general, for a changing work such as this, it should be a range of years from the year it was first published to the current year.

However, I'm inclined to suggest we just remove the year. The important part for anyone looking is who owns the copyright.

**Comment by shana** [comment]
After much pondering and discussion, the conclusion is that yeah, we should nuke the year altogether!

**Comment by shana** [comment]
celebrate

**Comment by marlazinger200** [comment]
1

**Pull request merged**
