### PR TITLE
Make sure our assembly resolver always run

### LINKED ISSUE #267: Property page doesn't load
image

Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA493
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA493
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA493
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   5.2.60328.3
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Atomineer Pro Documentation   1.0
Source-code documentation-comment creation and maintenance, and other documentation-related tools.

Clang with Microsoft CodeGen   14.0.25115
Clang with Microsoft CodeGen

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 10.0.2   Build 104.0.20151218.120627
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Node.js Tools   1.1.31117.00
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.1.31117.00
Profiling support for Node.js projects.

NuGet Package Manager   3.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

TypeScript   1.8.29.0
TypeScript tools for Visual Studio

VisualHG   1.1.7
Mercurial source contol provider.

### PR DESCRIPTION
**Pull request by shana**
Fixes #267

For some reason, the xaml loader fails miserably when trying to resolve where to load our DLLs from if they're not yet in the process. The directories it's scanning don't include the extension installation path,
so it can't find any assemblies that are referenced directly from xaml (using types from other assemblies in code works fine, using them in xaml doesn't).

The way to repro bug #267 is to set Solution Explorer as the focused pane and then restart VS, so that the next time it starts up it doesn't load Team Explorer by default (which means our assemblies won't get loaded beyond just the package initialization). Then go to Tools / Options and try to load the GitHub property page. It fails miserably.

We have an assembly resolver code path as part of our ResourceDictionary implementation (SharedDictionaryManager), so every xaml user control needs to have at least one include that uses SharedDictionaryManager in order to trigger the assembly resolver hook up and ensure that libraries
are found.

I just moved the styles declarations to a separate file so that we have a good reason to use the `SharedDictionaryManager` here.

This feels like a weird VS bug, probably a good idea to do a small repro for Microsoft.

### CODE REVIEW

**Comment by shana** [comment]
@Haacked @grokys @paladique for 👀  and perhaps a commiserating chuckle at the weird bugs we get.

**Comment by grokys** [comment]
Could adding the assembly resolution to a base class of `UserControl` make this a little more discoverable? Or does the XAML designer not handle subclasses of `UserControl` properly still? I've not tried it for a long time...

**Comment by shana** [comment]
> Could adding the assembly resolution to a base class of UserControl make this a little more discoverable?

Most of our user controls are subclasses, but not this one haha. But you know, maaaybe I should just add the resolver to the package entry point class instead, that one will always run. :P

**Comment by shana** [comment]
There, this will make sure the resolver is always hooked up.

**Comment by Haacked** [comment]
> This feels like a weird VS bug, probably a good idea to do a small repro for Microsoft.

Yeah, let's get our friends over there to look at it. Perhaps start with @acangialosi and @artl93 to help us find the right person to look at it.

**Comment by shana** [comment]
@Haacked I've created a separate issue for doing the repro of this bug. Is this good to merge? I think I want to do a release with this and some other bugfixes next week.

**Pull request merged**
