### PR TITLE
Fix null commit author

### PR DESCRIPTION
**Pull request by michaelbayles**
If the `author` is null for a particular commit, the entire Pull Request cannot load. This simple fix looks into the commit authorship instead

### CODE REVIEW

**Comment by meaghanlewis** [comment]
👋 @michaelbayles, thank you for your contribution! 🎉 

@jcansdale @StanleyGoldman can you help review this PR please?

**Comment by StanleyGoldman** [comment]
Hey @michaelbayles thanks for catching this.
I was looking at something completely unrelated and ran into the same bug, traced it down and realized you started on it.

**Comment by StanleyGoldman** [comment]
Related #2276

**Comment by StanleyGoldman** [comment]
Fixes #2276

**Comment by StanleyGoldman** [comment]
Thanks for starting this off @michaelbayles

**Pull request merged**
