### PR TITLE
[WIP] Get latest version of GHfVS build nightly using VSIX Gallery

### PR DESCRIPTION
**Pull request by meaghanlewis**
Use Mad Kristensen's [VSIX Gallery](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VSIXGallery-nightlybuilds) to get nightly builds of GHfVS.

Closes https://github.com/github/VisualStudio/issues/1317

### CODE REVIEW

**Comment by meaghanlewis** [comment]
👋  @jcansdale do you think you could help me out with this? 🙏 

I followed the instructions in: http://vsixgallery.com/guide/dev/ and first tried this from powershell by executing the VSIX script and then calling a method to upload the extension to the [VSIX 
 Gallery](http://vsixgallery.com/). That part was a breeze.

I added the same two steps in the `appveyor.yml` but the builds are not uploading from Appveyor. I looked through the [script code](https://github.com/madskristensen/ExtensionScripts/blob/master/AppVeyor/vsix.ps1) to see if im missing something obvious, but can't tell.

Mind taking a 👀 ?

**Comment by shana** [comment]
@meaghanlewis It looks like by default the script looks for a vsix in the current directory https://github.com/madskristensen/ExtensionScripts/blob/master/AppVeyor/vsix.ps1#L12

You likely need to pass in the path to the vsix in order to get it working.

Also, this is hooking up into every build we do, not just beta builds, which means we'd be publishing random builds from incomplete PR branches, too... not sure that's what we really want to do?

**Comment by meaghanlewis** [comment]
Thanks for taking a look on this @shana, this PR was pretty stale.

I did previously specify the path to the vsix as `c:\projects\visualstudio\release\**\*.vsix` - which didn't work although im pretty sure that path is correct.

And no, it wouldn't be a good idea to push that many builds to the VSIX Gallery, especially when some builds might be broken and users can end up trying those builds. We thought this could be a good way to easily grab new and install new builds to test, but it's just as easy to download and install builds from Appveyor instead. I also don't see a way we could pick and choose what builds get sent to the gallery.

I think it might be best to decide not to finish implementing this and close the issue.

**Comment by meaghanlewis** [comment]
Closing out this PR because we don't want every one of our AppVeyor builds to be uploaded to the VSIX Gallery

**Pull request closed without merging**
