### PR TITLE
Removed PR details ListView.

### LINKED ISSUE #825: Changed file table columns keep ending up too narrow
- GitHub Extension for Visual Studio  version: 2.2.0.6
- Visual Studio version: 2015

The change file columns keep ending up compressed. All I did was change PR.

image

### LINKED ISSUE #865: Remove ListView from Pull Request Details
The `ListView` in the pull request details pane is causing #825 due to a bug in WPF. After talking about it, we've decided to remove the `ListView` leaving only the `TreeView` as we don't see much use for the `ListView` anyway. Along with this change, the burger menu should also be removed as it will no longer be necessary.

### LINKED ISSUE #872: Pull request screen, Changes drop down menu icon hard to see in dark theme
GitHub Extension for Visual Studio version: 2.2.0.6
Visual Studio version: 2015 update 3

The icon for the menu to the right of the changes node isn't right on a dark theme, and can't be seen very well.

image

Black on dark grey not the easiest combination to see 😉

### PR DESCRIPTION
**Pull request by grokys**
Fixes #865.
Fixes #825.
Fixes #872.

### CODE REVIEW

**Comment by jcansdale** [comment]
Build failed. Can't find UnitTests.dll?

**Comment by grokys** [comment]
Passing now!

**Comment by grokys** [comment]
Ah! That node should say "Changes (#)" like the Team Explorer changes pane does, it shouldn't be blank! Well spotted.

**Comment by grokys** [comment]
@jcansdale changed files count is now displayed there. I noticed #879 while fixing it, but will fix that in separate PR.

**Pull request merged**
