### PR TITLE
Disable MEF services that are derived from VS services when executing in Blend

### LINKED ISSUE #1620: After installing extension in VS, Blend hits NullReferenceException when loading solution
- GitHub Extension for Visual Studio version: 2.5.1.2234
- Visual Studio version: 15.6.6
Note that GitHub appears in the list of extensions for VS, but not for Blend.

When loading a WPF solution Blend I hit an exception.
Here are the relevant parts of the Blend ActivityLog.xaml:

  <entry>
    <record>194</record>
    <time>2018/04/20 17:14:08.602</time>
    <type>Error</type>
    <source>Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost</source>
    <description>Still unable to load MEF component DLL: Could not load file or assembly &apos;Microsoft.TeamFoundation.Git.Provider, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\GITHUB\GITHUB\GitHub.TeamFoundation.14.dll</path>
  </entry>

  <entry>
    <record>379</record>
    <time>2018/04/20 17:14:08.702</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\GITHUB\GITHUB\</path>
  </entry>

  <entry>
    <record>380</record>
    <time>2018/04/20 17:14:08.702</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\GITHUB\GITHUB\</path>
  </entry>

  <entry>
    <record>514</record>
    <time>2018/04/20 17:14:13.841</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at GitHub.InlineReviews.InlineCommentMarginProvider.IsMarginDisabled(IWpfTextViewHost textViewHost) in C:\projects\visualstudio\src\GitHub.InlineReviews\InlineCommentMarginProvider.cs:line 98&#x000D;&#x000A;   at GitHub.InlineReviews.InlineCommentMarginProvider.CreateMargin(IWpfTextViewHost wpfTextViewHost, IWpfTextViewMargin parent) in C:\projects\visualstudio\src\GitHub.InlineReviews\InlineCommentMarginProvider.cs:line 70&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.&lt;AddMargins&gt;b__25_1(IWpfTextViewMarginProvider mp)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>

### PR DESCRIPTION
**Pull request by jcansdale**
Since custom VS services are disabled in Blend, we need to disable any of our MEF services that are derived from VS services.

### What this PR does

- Fix `ExportForProcessAttribute` so that when not executing in a specific named process the export `ContractName` is set to `GitHub.Disabled`
- Add `ExportForVisualStudioProcessAttribute` to conditionally export when executing in Visual Studio (`devenv`)
- Add `IsVisualStudioProcess` method to check when exports are available
- Disable `UIContext_Git` when not running in Visual Studio process
- Disable GitHub/InlineReviews commands when not running in Visual Studio process
- Disable GitHub options when when not running in Visual Studio process (previously it crashed)

Previously it was setting the `ContractType` to `null` when not executing in the named process. This made it use the default `ContractType` instead of the explicit contract interface. This happened to work when `[ExportForProcess(typeof(IFoo), "devenv")]` was on class `Foo`, because the default `ContractType` was `Foo` not `IFoo`. This didn't work when `[ExportForProcess(typeof(IFoo), "devenv")]` was on a property of type `IFoo`, because the default `ContractType` was exactly the same as the explicit contract interface.

This this PR makes sets the `ContractName` to `GitHub.Disabled` not executing in the named process. Since we import using using [Import(typeof(IFoo))] rather than  [Import("GitHub.Disabled", typeof(IFoo))], the service is effectively disabled. The disabled contract is given the unique name `GitHub.Disabled` to avoid unlikely possibility of a collision.

The following will still appear in the Blend UI:
image

image

When either of these buttons is clicked on, the following dialog will appear:
image
(not this has been changed from `Expression Blend` to just `Blend`)

### The regression

This fixes a regression that appeared when I changed to using property based exports, e.g:
https://github.com/github/VisualStudio/blob/e4bf7e110fc19c29ecfaad515d10a790e35e2014/src/GitHub.VisualStudio/GitHubPackage.cs#L126

Previously only the following would have worked as intended.
```cs
[ExportForProcess(typeof(IFoo), "devenv")]
public class Foo {
```

Now the following will also work correctly:
```cs
[ExportForProcess("devenv")]
public IFoo Foo { get; }
```

### What this PR doesn't do

There are some remnants that will still appear that are difficult to get rid of. The main thing is they won't crash Blend when clicked on!

image

### Reviewers

Previously clicking on any of the remnants above would crash Blend.

@meaghanlewis this might be worth putting into the test plan...

Check that selecting any of the following doesn't crash Blend:
`Other Widows > GitHub`
`Manage connections > Connect to GitHub`
`Options > GitHub for Visual Studio`

Fixes #1620

### CODE REVIEW

**Comment by jcansdale** [comment]
For reference, here's what the MEF looks like when the extension is loaded in Blend:
```
----- CompositionError level 1 ------
GitHub.InlineReviews.Commands.NextInlineCommentCommand.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.InlineReviews.Commands.NextInlineCommentCommand

GitHub.InlineReviews.InlineCommentMarginProvider.ctor(packageSettings): expected exactly 1 export of GitHub.Settings.IPackageSettings but found 0.
   part definition GitHub.InlineReviews.InlineCommentMarginProvider

GitHub.InlineReviews.InlineCommentMarginProvider.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.InlineReviews.InlineCommentMarginProvider

GitHub.VisualStudio.SelectedTextProvider.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.SelectedTextProvider

GitHub.Services.UsageService.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.Services.UsageService

GitHub.InlineReviews.Services.InlineCommentPeekService.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.InlineReviews.Services.InlineCommentPeekService

GitHub.VisualStudio.Commands.OpenPullRequestsCommand.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.Commands.OpenPullRequestsCommand

GitHub.VisualStudio.UI.Services.ShowDialogService.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.UI.Services.ShowDialogService

GitHub.ViewModels.Dialog.GistCreationViewModel.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.ViewModels.Dialog.GistCreationViewModel

GitHub.VisualStudio.Base.TeamExplorerServiceHolder.ctor(gitService): expected exactly 1 export of GitHub.Services.IVSGitExt but found 0.
   part definition GitHub.VisualStudio.Base.TeamExplorerServiceHolder

GitHub.Factories.ViewViewModelFactory.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.Factories.ViewViewModelFactory

GitHub.Services.TeamExplorerContext.ctor(gitExt): expected exactly 1 export of GitHub.Services.IVSGitExt but found 0.
   part definition GitHub.Services.TeamExplorerContext

GitHub.Services.TeamExplorerContext.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.Services.TeamExplorerContext

GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection1.ctor(settings): expected exactly 1 export of GitHub.Settings.IPackageSettings but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection1

GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection1.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection1

GitHub.VisualStudio.Commands.OpenLinkCommand.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.Commands.OpenLinkCommand

GitHub.ViewModels.TeamExplorer.RepositoryPublishViewModel.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.ViewModels.TeamExplorer.RepositoryPublishViewModel

GitHub.App.Services.GlobalConnection.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.App.Services.GlobalConnection

GitHub.VisualStudio.TeamExplorer.Home.PulseNavigationItem.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Home.PulseNavigationItem

GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection0.ctor(settings): expected exactly 1 export of GitHub.Settings.IPackageSettings but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection0

GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection0.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection0

GitHub.ViewModels.Dialog.RepositoryCreationViewModel.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.ViewModels.Dialog.RepositoryCreationViewModel

GitHub.VisualStudio.Commands.ShowGitHubPaneCommand.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.Commands.ShowGitHubPaneCommand

GitHub.VisualStudio.Commands.SyncSubmodulesCommand.ctor(gitExt): expected exactly 1 export of GitHub.Services.IVSGitExt but found 0.
   part definition GitHub.VisualStudio.Commands.SyncSubmodulesCommand

GitHub.VisualStudio.TeamExplorer.Home.GitHubHomeSection.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Home.GitHubHomeSection

GitHub.VisualStudio.TeamExplorer.Home.GitHubHomeSection.ctor(settings): expected exactly 1 export of GitHub.Settings.IPackageSettings but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Home.GitHubHomeSection

GitHub.VisualStudio.TeamExplorer.Home.GitHubHomeSection.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Home.GitHubHomeSection

GitHub.InlineReviews.Services.PullRequestSessionService.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.InlineReviews.Services.PullRequestSessionService

GitHub.VisualStudio.Views.Dialog.GistCreationView.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.Views.Dialog.GistCreationView

GitHub.VisualStudio.ConnectionManager.ctor(loginManager): expected exactly 1 export of GitHub.Api.ILoginManager but found 0.
   part definition GitHub.VisualStudio.ConnectionManager

GitHub.VisualStudio.ConnectionManager.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.VisualStudio.ConnectionManager

GitHub.VisualStudio.TeamExplorer.Connect.GitHubInvitationSection.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Connect.GitHubInvitationSection

GitHub.Services.PullRequestService.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.Services.PullRequestService

GitHub.VisualStudio.TeamExplorer.Home.PullRequestsNavigationItem.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Home.PullRequestsNavigationItem

GitHub.VisualStudio.TeamExplorer.Home.PullRequestsNavigationItem.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Home.PullRequestsNavigationItem

GitHub.InlineReviews.Services.PullRequestStatusBarManager.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.InlineReviews.Services.PullRequestStatusBarManager

GitHub.Services.PullRequestEditorService.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.Services.PullRequestEditorService

GitHub.Services.PullRequestEditorService.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.Services.PullRequestEditorService

GitHub.VisualStudio.TeamExplorer.Home.IssuesNavigationItem.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Home.IssuesNavigationItem

GitHub.VisualStudio.Commands.CopyLinkCommand.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.Commands.CopyLinkCommand

GitHub.Services.RepositoryCloneService.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.Services.RepositoryCloneService

GitHub.Services.VSGitServices.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.Services.VSGitServices

GitHub.ViewModels.GitHubPane.PullRequestDetailViewModel.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.ViewModels.GitHubPane.PullRequestDetailViewModel

GitHub.Services.TeamExplorerServices.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.Services.TeamExplorerServices

GitHub.InlineReviews.Commands.PreviousInlineCommentCommand.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.InlineReviews.Commands.PreviousInlineCommentCommand

GitHub.VisualStudio.Commands.ShowCurrentPullRequestCommand.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.Commands.ShowCurrentPullRequestCommand

GitHub.VisualStudio.TeamExplorer.Home.WikiNavigationItem.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Home.WikiNavigationItem

GitHub.VisualStudio.Commands.BlameLinkCommand.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.Commands.BlameLinkCommand

GitHub.ViewModels.GitHubPane.PullRequestListViewModel.ctor(settings): expected exactly 1 export of GitHub.Settings.IPackageSettings but found 0.
   part definition GitHub.ViewModels.GitHubPane.PullRequestListViewModel

GitHub.Services.VSServices.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.Services.VSServices

GitHub.ViewModels.GitHubPane.GitHubPaneViewModel.ctor(usageTracker): expected exactly 1 export of GitHub.Services.IUsageTracker but found 0.
   part definition GitHub.ViewModels.GitHubPane.GitHubPaneViewModel

GitHub.VisualStudio.TeamExplorer.Home.GraphsNavigationItem.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Home.GraphsNavigationItem

GitHub.VisualStudio.TeamExplorer.Sync.GitHubPublishSection.ctor(serviceProvider): expected exactly 1 export of GitHub.Services.IGitHubServiceProvider but found 0.
   part definition GitHub.VisualStudio.TeamExplorer.Sync.GitHubPublishSection

----- CompositionError level 2 ------
GitHub.ViewModels.GitHubPane.PullRequestCreationViewModel.ctor(service): expected exactly 1 export of GitHub.Services.IPullRequestService but found 0.
   part definition GitHub.ViewModels.GitHubPane.PullRequestCreationViewModel

GitHub.ViewModels.GitHubPane.NotAGitHubRepositoryViewModel.ctor(teamExplorerServices): expected exactly 1 export of GitHub.Services.ITeamExplorerServices but found 0.
   part definition GitHub.ViewModels.GitHubPane.NotAGitHubRepositoryViewModel

GitHub.ViewModels.Dialog.RepositoryCloneViewModel.ctor(cloneService): expected exactly 1 export of GitHub.Services.IRepositoryCloneService but found 0.
   part definition GitHub.ViewModels.Dialog.RepositoryCloneViewModel

GitHub.ViewModels.GitHubPane.PullRequestReviewAuthoringViewModel.ctor(editorService): expected exactly 1 export of GitHub.Services.IPullRequestEditorService but found 0.
   part definition GitHub.ViewModels.GitHubPane.PullRequestReviewAuthoringViewModel

GitHub.ViewModels.Dialog.GitHubDialogWindowViewModel.ctor(factory): expected exactly 1 export of GitHub.Factories.IViewViewModelFactory but found 0.
   part definition GitHub.ViewModels.Dialog.GitHubDialogWindowViewModel

GitHub.ViewModels.Dialog.GitHubDialogWindowViewModel.ctor(connectionManager): expected exactly 1 export of GitHub.Services.IConnectionManager but found 0.
   part definition GitHub.ViewModels.Dialog.GitHubDialogWindowViewModel

GitHub.ViewModels.Dialog.RepositoryRecloneViewModel.ctor(cloneService): expected exactly 1 export of GitHub.Services.IRepositoryCloneService but found 0.
   part definition GitHub.ViewModels.Dialog.RepositoryRecloneViewModel

GitHub.VisualStudio.Commands.CreateGistCommand.ctor(selectedTextProvider): expected exactly 1 export of GitHub.Services.ISelectedTextProvider but found 0.
   part definition GitHub.VisualStudio.Commands.CreateGistCommand

GitHub.Services.LocalRepositories.ctor(vsGitServices): expected exactly 1 export of GitHub.Services.IVSGitServices but found 0.
   part definition GitHub.Services.LocalRepositories

GitHub.ViewModels.Dialog.LoginToGitHubViewModel.ctor(connectionManager): expected exactly 1 export of GitHub.Services.IConnectionManager but found 0.
   part definition GitHub.ViewModels.Dialog.LoginToGitHubViewModel

GitHub.ViewModels.Dialog.LoginCredentialsViewModel.ctor(connectionManager): expected exactly 1 export of GitHub.Services.IConnectionManager but found 0.
   part definition GitHub.ViewModels.Dialog.LoginCredentialsViewModel

GitHub.Services.RepositoryCreationService.ctor(cloneService): expected exactly 1 export of GitHub.Services.IRepositoryCloneService but found 0.
   part definition GitHub.Services.RepositoryCreationService

GitHub.InlineReviews.Services.PullRequestSessionManager.ctor(service): expected exactly 1 export of GitHub.Services.IPullRequestService but found 0.
   part definition GitHub.InlineReviews.Services.PullRequestSessionManager

GitHub.InlineReviews.Services.PullRequestSessionManager.ctor(sessionService): expected exactly 1 export of GitHub.InlineReviews.Services.IPullRequestSessionService but found 0.
   part definition GitHub.InlineReviews.Services.PullRequestSessionManager

GitHub.InlineReviews.Services.PullRequestSessionManager.ctor(teamExplorerContext): expected exactly 1 export of GitHub.Services.ITeamExplorerContext but found 0.
   part definition GitHub.InlineReviews.Services.PullRequestSessionManager

GitHub.InlineReviews.Services.PullRequestSessionManager.ctor(connectionManager): expected exactly 1 export of GitHub.Services.IConnectionManager but found 0.
   part definition GitHub.InlineReviews.Services.PullRequestSessionManager

GitHub.ViewModels.GitHubPane.PullRequestFilesViewModel.ctor(service): expected exactly 1 export of GitHub.Services.IPullRequestService but found 0.
   part definition GitHub.ViewModels.GitHubPane.PullRequestFilesViewModel

GitHub.ViewModels.GitHubPane.PullRequestFilesViewModel.ctor(editorService): expected exactly 1 export of GitHub.Services.IPullRequestEditorService but found 0.
   part definition GitHub.ViewModels.GitHubPane.PullRequestFilesViewModel

GitHub.InlineReviews.Peek.InlineCommentPeekableItemSourceProvider.ctor(nextCommentCommand): expected exactly 1 export of GitHub.Commands.INextInlineCommentCommand but found 0.
   part definition GitHub.InlineReviews.Peek.InlineCommentPeekableItemSourceProvider

GitHub.InlineReviews.Peek.InlineCommentPeekableItemSourceProvider.ctor(peekService): expected exactly 1 export of GitHub.InlineReviews.Services.IInlineCommentPeekService but found 0.
   part definition GitHub.InlineReviews.Peek.InlineCommentPeekableItemSourceProvider

GitHub.InlineReviews.Peek.InlineCommentPeekableItemSourceProvider.ctor(previousCommentCommand): expected exactly 1 export of GitHub.Commands.IPreviousInlineCommentCommand but found 0.
   part definition GitHub.InlineReviews.Peek.InlineCommentPeekableItemSourceProvider

GitHub.Services.DialogService.ctor(showDialog): expected exactly 1 export of GitHub.Services.IShowDialogService but found 0.
   part definition GitHub.Services.DialogService

GitHub.Services.DialogService.ctor(factory): expected exactly 1 export of GitHub.Factories.IViewViewModelFactory but found 0.
   part definition GitHub.Services.DialogService

GitHub.Services.RepositoryPublishService.ctor(vsGitServices): expected exactly 1 export of GitHub.Services.IVSGitServices but found 0.
   part definition GitHub.Services.RepositoryPublishService

GitHub.ViewModels.GitHubPane.PullRequestUserReviewsViewModel.ctor(editorService): expected exactly 1 export of GitHub.Services.IPullRequestEditorService but found 0.
   part definition GitHub.ViewModels.GitHubPane.PullRequestUserReviewsViewModel

GitHub.VisualStudio.Views.TeamExplorer.RepositoryPublishView.ctor(teServices): expected exactly 1 export of GitHub.Services.ITeamExplorerServices but found 0.
   part definition GitHub.VisualStudio.Views.TeamExplorer.RepositoryPublishView

GitHub.ViewModels.Dialog.LoginToGitHubForEnterpriseViewModel.ctor(connectionManager): expected exactly 1 export of GitHub.Services.IConnectionManager but found 0.
   part definition GitHub.ViewModels.Dialog.LoginToGitHubForEnterpriseViewModel

----- CompositionError level 3 ------
GitHub.ViewModels.Dialog.LoginViewModel.ctor(credentials): expected exactly 1 export of GitHub.ViewModels.Dialog.ILoginCredentialsViewModel but found 0.
   part definition GitHub.ViewModels.Dialog.LoginViewModel

GitHub.InlineReviews.Tags.InlineCommentTaggerProvider.ctor(sessionManager): expected exactly 1 export of GitHub.Services.IPullRequestSessionManager but found 0.
   part definition GitHub.InlineReviews.Tags.InlineCommentTaggerProvider

GitHub.ViewModels.GitHubPane.LoggedOutViewModel.ctor(dialogService): expected exactly 1 export of GitHub.Services.IDialogService but found 0.
   part definition GitHub.ViewModels.GitHubPane.LoggedOutViewModel

GitHub.VisualStudio.Commands.AddConnectionCommand.ctor(dialogService): expected exactly 1 export of GitHub.Services.IDialogService but found 0.
   part definition GitHub.VisualStudio.Commands.AddConnectionCommand
```

**Comment by meaghanlewis** [comment]
Tested this using Blend for VS 2015 and 2017. Can confirm that Blend no longer crashes or displays errors when trying to use/view GitHub functionality. Thanks @jcansdale ✨ 

One thing I find interesting is that even when the GitHub extension is disabled I still see these options in Blend:
- Other Widows > GitHub
- Manage connections > Connect to GitHub
- Options > GitHub for Visual Studio

**Comment by jcansdale** [comment]
@meaghanlewis,

> One thing I find interesting is that even when the GitHub extension is disabled I still see these options in Blend

Yes, this is unfortunately. Unfortunately there isn't an easy way to fix without degrading startup performance when the extension is running in Visual Studio. Here are some notes:

> - Other Widows > GitHub

This button is default visible and loads the GitHubPackage when clicked.

> - Manage connections > Connect to GitHub

I believe this command it also default visible and loads the GitHubPackage when clicked.

> - Options > GitHub for Visual Studio

Don't think there's any support for dynamically enabling/disabling options.

We could maybe show a warning dialog when the user clicks on one of those buttons saying the extension is only supported in VS?

**Comment by meaghanlewis** [comment]
This LGTM. Thanks so much for adding the dialog that shows after selecting any GitHub functionality. ✨ 
 It will make it clearer to users that we don't support Blend.

screen shot 2018-05-16 at 8 58 49 am

**Comment by jcansdale** [comment]
@meaghanlewis,

> It will make it clearer to users that we don't support Blend.

Yes, I think it will. The user who originally reported the issue also commented on this: https://github.com/github/VisualStudio/issues/1620#issuecomment-387878037

**Pull request merged**
