### PR TITLE
Correctly validate source branch in PR creation.

### LINKED ISSUE #455: "Source branch does not exist remotely" being shown when creating PR, though it does exist remotely
Using 2.0.0 RC1 the following message is shown:

image

Even when the source branch does exist remotely.

This is happening because [`BranchValidator`](https://github.com/github/VisualStudio/blob/master/src/GitHub.App/ViewModels/PullRequestCreationViewModel.cs#L58) is first called with `null` before being called with the `BranchModel`.

### PR DESCRIPTION
**Pull request by grokys**
Don't try to validate source branch using `BranchValidator` while initialization is in progress. Fixes #455.

### CODE REVIEW

**Comment by shana** [comment]
This is failing CI 😢

**Comment by grokys** [comment]
Now passing :)

**Comment by shana** [comment]
Oh, damnit, the other PR got merged and now they're conflicting :(

**Comment by grokys** [comment]
Ok, will fix!

**Comment by paladique** [comment]
:+1: LGTM!

**Pull request merged**
