### PR TITLE
Style inline annotations

### PR DESCRIPTION
**Pull request by donokuda**
This pull request styles the inline annotation work that @StanleyGoldman started on:

**Warning + Error states + Info state** (Blue theme)
screen shot 2018-10-30 at 1 44 02 pm
screen shot 2018-10-30 at 1 43 31 pm

**Dark theme example**
screen shot 2018-10-30 at 2 25 37 pm

**Light theme example**
screen shot 2018-10-30 at 2 26 46 pm

### CODE REVIEW

**Comment by donokuda** [comment]
Also styled the comments:

image

**Comment by donokuda** [comment]
Updated the border color for comments and annotation blocks so that it works for all themes:

**Light:**
screen shot 2018-11-07 at 2 25 53 pm

**Dark:**
screen shot 2018-11-07 at 2 25 31 pm

**Blue:**
screen shot 2018-11-07 at 2 19 37 pm

**Comment by donokuda** [comment]
Heads up: these changes are ready for review and I don't plan on adding more changes to it at this time (feedback pending of course.)

**Comment by StanleyGoldman** [comment]
This is awesome.

**Pull request merged**
