### PR TITLE
Change Not git repo message

### PR DESCRIPTION
**Pull request by micheleissa**
- Per #1727  change the text of the message.

### CODE REVIEW

**Comment by grokys** [comment]
Thanks @micheleissa! I'm wondering if we should maybe have two messages: one for when there's no solution opened and one for when there's a solution opened but it's not a git repository? Not sure really, @sguthals what do you think?

**Comment by jcansdale** [comment]
@grokys,

> I'm wondering if we should maybe have two messages: one for when there's no solution opened and one for when there's a solution opened but it's not a git repository?

I think we should do this with another message for when a repository exists but there is no `origin` remote defined. At the moment users are given no clues as to what's going on.

**Comment by grokys** [comment]
Yeah, possibly, but that sounds like a separate PR to me?

**Comment by jcansdale** [comment]
> Yeah, possibly, but that sounds like a separate PR to me?

I just wanted to mention there were a few different things we might want to check for -- eventually. 😄

**Comment by micheleissa** [comment]
So will this pr be accepted or not?

**Comment by sguthals** [comment]
@grokys yes! I agree with:
> one for when there's no solution opened and one for when there's a solution opened but it's not a git repository?

@micheleissa Are you up for making that distinction as part of this pr?

**Comment by micheleissa** [comment]
@sguthals I can try if it is easy to know there is a an opened non-git solution. I might ask for some directions.

**Comment by micheleissa** [comment]
I'm not familiar at all with Xaml so I don't know where to begin..all I know for now is the view GenericNotAGitRepositoryView is using NotAGitRepositoryMessage resource. Could you guys shed some light on that and where does this panel even displayed?

**Comment by micheleissa** [comment]
@grokys  thanks. Do I need to check in https://github.com/github/VisualStudio/blob/master/src/GitHub.App/ViewModels/GitHubPane/GitHubPaneViewModel.cs#L396-L407 if a solution open or not and also for a msg if not a git repo I think this is handled already.

**Comment by grokys** [comment]
@micheleissa yes that's what you'll need to do. You'll want to abstract the "is a solution open?" check into a service so that it can be unit tested.

**Comment by StanleyGoldman** [comment]
Hey @micheleissa are you still interested in working on this?

**Comment by micheleissa** [comment]
I might take a look at it this weekend. Do you guys have a deadline for it?

**Comment by vbarcaru** [comment]
I'm not working yet

**Comment by meaghanlewis** [comment]
No, there is no deadline @micheleissa. Just wondering if you were still interested in completing this work.

**Comment by micheleissa** [comment]
@meaghanlewis thank you, I'm trying to re-produce the issue but I can't. Have any of you guys managed to produce it and if so could you tell me how? Thanks again.

**Comment by jcansdale** [comment]
Closing some very old PRs.

**Pull request closed without merging**
