### PR TITLE
Polish sign out required dialog

### PR DESCRIPTION
**Pull request by donokuda**
Destination Branch: `grokys/feature/gist-support`

Before:

BEFOREEEEEEEEE

After:

screen shot 2016-05-26 at 11 30 21 am

cc @niik and @simurai for 👀

### CODE REVIEW

**Comment by shana** [comment]
This looks great! At this point, I'm only wondering if the message should be tweaked or not. Is it confusing, not clear enough, will they be scared of doing this?

@Haacked @pmn @paladique thoughts?

**Comment by Haacked** [comment]
What does "this feature" refer to?

**Comment by shana** [comment]
@Haacked It's the "creating a gist" feature. Sounds like we should probably be explicit here and say "To create a Gist, you need to sign in again"?

**Comment by Haacked** [comment]
I think being explicit is good here. I mean, for most users they'll understand  the context. But I could imagine invoking the operation, switching to another task, coming back and not remembering what "this feature" refers to.

**Comment by paladique** [comment]
:+1: to being more explicit, and specifically for wording also agree with replacing "feature" with "creating a gist"

**Comment by simurai** [comment]
>  you need to sign in again.

It might be confusing to say they have to "sign in" but then the button says "Sign out". How about:

`To create a Gist, you need to sign out and then sign in again.`

Although that sounds a bit cumbersome. 🙉

**Comment by shana** [comment]
> It might be confusing to say they have to "sign in" but then the button says "Sign out".

Yeah, I was finding that discrepancy a bit jarring too. Maybe `To create a Gist, you need to sign out and in again.`?

**Comment by grokys** [comment]
Have we come to a conclusion on this? Once this is decided, I think we're ready to merge gists into master.

**Comment by grokys** [comment]
"To create a Gist you need to sign out and back in"?

**Comment by shana** [comment]
I've done a few tweaks to this so that the message and the icon can be set dynamically depending on which feature actually ends up in this dialog. If we ever need to add more scopes or force log outs for some reason, we can just reuse this.

**Comment by shana** [comment]
How it looks now:

screen shot 2016-05-27 at 2 48 49 pm

**Pull request merged**
