### PR TITLE
Issue template

### LINKED ISSUE #333: Issue submission guidelines
We have a contributor guide for PRs, but not for Issues. This is in anticipation of issues that might be created in relation to the new features we're currently working on. 

I'm thinking we'd add this on to `contributing.md`, to include how to make a log file, and how screenshots, in addition to those log files, will be helpful in diagnosing problems.

Making Issue templates might work too!
Anything else that would be helpful? cc: @shana @Haacked @grokys 

- [x] Add Issue submission info in `contributing.md` 
- [ ] Create Issue templates

### PR DESCRIPTION
**Pull request by paladique**
:thought_balloon: if it's better to make a checklist, or just a blurb that says to check out  `contributing.md` when submitting (which is what is currently there). Fixes #333

### CODE REVIEW

**Comment by shana** [comment]
Hmm, good question. A blurb might be enough, not sure if we can create a checklist that would cover the issues that people incorrectly report.

**Comment by shana** [comment]
Looks like we need to merge this sooner rather than later, yet another non-related issue popped up. Let's add some more stuff in here:

```
### Version of the GitHub Extension
The version of the extension is at `Tools\Extensions\Installed - GitHub Extension for Visual Studio`

### Version of Visual Studio
The version of VS is on the `Help\About`, on the top left, above the copyright line.

### What happened
Tell us what went wrong

### Steps to reproduce
```

**Comment by paladique** [comment]
This, with the added suggestions should be pretty solid for informing contributors before posting

**Comment by shana** [comment]
✨

**Pull request merged**
