### PR TITLE
Adds sign-in button to Repository Home Page

### LINKED ISSUE #56: Add sign-in button to Repository Home Page
When the user is unauthenticated and they visit a repository's home page in team explorer, we should provide a visual indication that they are not logged in and an option to log in. Something like this:

Home page with sign in button

When they log in, the "sign in..." button goes away.

### PR DESCRIPTION
**Pull request by tocsoft**
When dealing with a github repo and user has signed out they are given a hint/link to sign in which start the authentication flow.

image

resolves #56

### CODE REVIEW

**Comment by shana** [comment]
This is probably conflicting with your other signing PR that just got merged :P

**Comment by tocsoft** [comment]
all merged 😸 and building

**Comment by tocsoft** [comment]
prod 👉  *GitHub CLA* you look broken 👀

**Comment by shana** [comment]
Yeah dunno what's up with that :P

**Comment by grokys** [comment]
Thanks @tocsoft - this works great! Sorry for the delay in merging! 🎇

**Pull request merged**
