### PR TITLE
[Backport] Add directory validation

### PR DESCRIPTION
**Pull request by paladique**
For the upcoming hot-fix release listed in #368, it was decided that the resolution to #360 should be in this release. Picked those commits.

### CODE REVIEW

**Comment by paladique** [comment]
I should probably hold off on picking the rest of this until the second part is complete.

**Comment by paladique** [comment]
So `release/1.0.18` doesn't include the binding fixes from

**Comment by paladique** [comment]
Somehow after picking all commits from #369 it looks like there was still a reference to two files that didn't exist. I just removed them and tested to make sure everything was :+1:

**Comment by shana** [comment]
This looks good! 👍

**Pull request merged**
