### PR TITLE
[SPIKE] Don't do "clean" check before attempting to check-out PR

### LINKED ISSUE #1271: Can't checkout PR when there are untracked files
- GitHub Extension for Visual Studio version: 2.3.3.38
- Visual Studio version: Add

The extension often won't let me checkout PR branches.

image

This can be due to trivial things like build artifacts being added to the staging area.

image

This can be caused by build artifacts/tools (NCrunch) adding files to the working directory. Untracked files usually wouldn't be a problem when using Git from the command line, they can be a real nuisance when using the extension.

This is particularly problematic when the untracked files appear in submodules. The Git command line arguments necessary to clean them up aren't at all obvious (to me at least).

The current check is done here:
https://github.com/github/VisualStudio/blob/a480116a45053b43a3175d37603e117caa0234c5/src/GitHub.App/Services/PullRequestService.cs#L89

It uses `IsDirty`, which checks for any differences between the working directory/index and the last comment. By default, command line Git will allow a checkout if there are untracked files in the working directory.

This issue is even more insidious when an untracked file gets added to a submodule. Here I'ved added `foo.txt` to the `splat` submodule.

Visual Studio (below) and the Git command line doesn't give much of a clue as to what's going wrong. You can see that something might be up with the `splat` submodule, but it doesn't give any indication of exactly what.

image

### PR DESCRIPTION
**Pull request by jcansdale**
NOTE: This PR is intended for experimenting with functionality rather than necessarily merging.

In previous versions, the PR `Checkout` link was only active if the working directory and latest commit where exactly the same. There isn't this restriction when checking out using command line Git.

In #1302 this restriction is relaxed a bit to allow untracked files in the staging area (often build artifacts or log files). This PR changes it to behave more like the command line. It will always attempt a checkout and inform the user if it fails.

- For example, if the user makes a local change.

image

The `Checkout` command will work and bring that change to the PR branch. There currently isn't any indication that there are local changes when using the PR pane.

- If there are local changes that conflict with the PR being checked out, an error message will be displayed.

image

It doesn't currently give any hints how to fix the conflicts. Maybe we should offer the user a link to the `Team Explorer - Changes` pane?

Fixes #1271.

### CODE REVIEW

**Comment by grokys** [comment]
> It doesn't currently give any hints how to fix the conflicts. Maybe we should offer the user a link to the Team Explorer - Changes pane?

Yes, I think that would be the best solution.

**Comment by jcansdale** [comment]
Here are some related issues:

Can't checkout PR when there are untracked files: https://github.com/github/VisualStudio/issues/1271
Submodules cause all kinds of issues when checking out a PR: https://github.com/github/VisualStudio/issues/826

**Comment by meaghanlewis** [comment]
Hey @jcansdale thanks for making these changes! I was testing this and have a few questions.

- Where does the message `1 conflict prevents checkout` come from? I can't find it in the codebase anywhere.
- I get the conflict message sometimes even when I've changed files that aren't related to a PR. For example, I changed a file (`src\GitHub.UI\GitHub.UI.csproj`) that wasn't included in the files changed in this PR and then tried to check out this branch `fixes/1271-just-try-PR-checkout`. This is unexpected, right?
- Is clicking `[GitChanges]` supposed to take me to Team Explorer - Changes? Currently it's not doing anything for me.
git changes

- Unrelated to functionality, but I noticed that tests were removed for this PR but no new ones were added. Should they be added? I'd be up to pair to add a test or two (especially because I currently have no idea how to write tests for this project)!

**Comment by jcansdale** [comment]
> Where does the message 1 conflict prevents checkout come from? I can't find it in the codebase anywhere.

This is a the message from a libgit2sharp exception that gets thrown when it fails to checkout (kind of like when command line Git can't do a checkout).

> I get the conflict message sometimes even when I've changed files that aren't related to a PR. For example, I changed a file (src\GitHub.UI\GitHub.UI.csproj) that wasn't included in the files changed in this PR and then tried to check out this branch fixes/1271-just-try-PR-checkout. This is unexpected, right?

I think changing files that are included in the PR might be okay, it's changing files that are changed on the target branch that is an issue.

> Is clicking [GitChanges] supposed to take me to Team Explorer - Changes? Currently it's not doing anything for me.

Yup, that is how it's supposed to work! I'll check.

> Unrelated to functionality, but I noticed that tests were removed for this PR but no new ones were added. Should they be added?

In this case the tests were for a method that has been removed. To test the new functionality, we would need to do integration tests against a real Git repo. This might be a little involved, so I think it would make sense to flesh out exactly how we want it to work before tackling this. It definitely makes sense to add them though.

**Comment by jcansdale** [comment]
This PR was an experiment at addressing #1271. This has since been fixed by the following PRs:

- Don't block checking out a PR if there are untracked files #1302 
- [Feature] Reviewing PR with submodule changes #1392

**Pull request closed without merging**
