### PR TITLE
Find merge base when external PR branch has been deleted

### LINKED ISSUE #1190: 'Couldn't find merge base' displayed when opening pull request
__Version__
- GitHub Extension for Visual Studio  version: 2.3.0.22
- Visual Studio version: 2017

__What happened__ 
I encountered this 'Couldn't find merge base..' exception after cloning the repo and then trying to open this PR: AvaloniaUI/Avalonia#1127
couldnt find merge base

This issue was consistently reproducible, but now I can't reproduce it anymore. Will add more details to this issue if I encounter this problem again.

### PR DESCRIPTION
**Pull request by jcansdale**
There was an issue when a PR has been submitted from a fork, the PR had been accepted and the owner deleted the PR branch. GitHub for Visual Studio was unable to find the original (now deleted) branch to show the PR details. This should allow those old PRs to still be displayed.

There are likely other edge cases that I need to think about (hence WIP for the moment).

Fixes #1190

### CODE REVIEW

**Comment by meaghanlewis** [comment]
I tested this with some PR's that I previously wasn't able to view, and they appear to load now with your fix. 👍

**Comment by jcansdale** [comment]
@meaghanlewis,

> I tested this with some PR's that I previously wasn't able to view, and they appear to load now with your fix. 

That is good news. I think this is by far the most common scenario. Someone submits a PR from and fork and deletes the branch once the PR has been accepted.

I'm trying to think what other possible edge cases there might be.  In the above case I was able to take advantage of the special `refs/pull/<PR>/head` branch name. It seems these remain available even after the PR has been closed and its branch deleted.

I'm wondering what would happen if the PR base branch has been deleted (there isn't an equivalent `refs/pull/<PR>/base`). Obviously this won't happen very often with the default `master` branch.

Could you try the following:

1. Create a PR from a fork onto a branch other than master.
2. Accept and close the PR.
3. Delete the branch the PR was merged onto.

- I'm interested to know if you can still view the PR details.
- There might be a difference between using an account that owns the repo and one that can only view it.
- Be sure to create a fresh clone of the repo (if the commits already exist, it won't need to fetch from the deleted branch)

**Comment by jcansdale** [comment]
> I'm wondering what would happen if the PR base branch has been deleted (there isn't an equivalent refs/pull/<PR>/base).

I've done some further testing with this. If the PR base branch has been deleted, we can's simply do a fetch using the base branch name (or SHA). This seems to be the case whether or not the user has permissions to undelete the branch.

As a workaround for this, I'm fetching the head branch using `refs/pull/<PR>/head`, before checking if the required base commits are available. This means that if the base is directly upstream of the head, there is no need to fetch the head branch (which will very often be the case).

The problematic case would be if commits have been added to the base branch of the PR, before the PR is closed and the base branch deleted (not just the head branch, which would be the usual case).

**Comment by jcansdale** [comment]
> The problematic case would be if commits have been added to the base branch of the PR, before the PR is closed and the base branch deleted (not just the head branch, which would be the usual case).

I've so far failed to produce this problematic case. Maybe it isn't an issue after all? 😕

**Pull request merged**
