### PR TITLE
Pull Request Filtering

### LINKED ISSUE #722: Add filtering and sorting to PR list.
When the pull request list is large, it can be hard to find the one you're looking for. It would be useful to have options for filtering (by number and title keyword) and sorting in the PR list.

### PR DESCRIPTION
**Pull request by grokys**
Adds a filter box to the pull request list.

image

This PR supersedes #732 - moving it to a branch in this repository so we can get artifacts.

Fixes #722

### CODE REVIEW

**Comment by meaghanlewis** [comment]
These changes LGTM ✅ . The filter box is really nice.

**Comment by jcansdale** [comment]
I've been using this and it's really useful functionality!

One thing that feels a little wrong. I want to be able to enter a PR number and hit return to open it (like you can with some other VS search boxes). This functionality would also be useful when in the PR details view, where you can see the search box but can't use it. Would either of these be appropriate for this PR?

**Comment by grokys** [comment]
Yes the search could be useful in the PR details view too, but we'd need to decide what it did. Filter the changed files list? Highlight the search term in the description?

For these reasons I felt it best just to disable it in the PR details for now, we can address searching there in another PR.

**Comment by grokys** [comment]
Hmm, hitting enter should work - it works for me at least.

**Comment by jcansdale** [comment]
@grokys,

> What other VS search boxes use hitting enter to navigate rather than submit the query immediately?

image

- The `Quick Launch` performs the action at the top of the list when you hit enter
- The toolbar `Search` searches the active document when you hit enter

**Comment by grokys** [comment]
Hmm, ok. To me these search bars are slightly different, in that they're not filters, but lets discuss this separately I'd say.

**Pull request merged**
