### PR TITLE
Fix DiffService warnings

### PR DESCRIPTION
**Pull request by Myoxocephalus**
Fixed CA1825 warnings in DiffService.
* Added tests to verify that that behavior wasn't change.
* Moved DiffUtilities test from DiffServiceTest to DiffUtilitiesTests.

### CODE REVIEW

**Comment by grokys** [comment]
Hi @Myoxocephalus - thanks for this. Could you update the description with some more info: what are the tests you added testing, and more importantly, why?

**Comment by Myoxocephalus** [comment]
Thanks @grokys! Both the title and description was a bit confusing but now it's updated to be more descriptive.

**Comment by meaghanlewis** [comment]
@grokys @jcansdale @StanleyGoldman can any of you provide feedback for this PR?

**Comment by StanleyGoldman** [comment]
Hey @Myoxocephalus sorry this sat in the ether for so long.
Thanks for the contribution.

**Pull request merged**
