### PR TITLE
Request the `workflow` scope

### LINKED ISSUE #2455: Push failed when update GitHub workflow file
## Versions
 - GitHub Extension for Visual Studio version: 2.10.8.8132
 - Visual Studio version: VS 2019 ENT (16.4.2)

## What happened
When I try to updated a GitHub workflow file (yaml file) the push will fail with following error:

Error encountered while pushing to the remote repository: rejected features/cicd -> features/cicd (refusing to allow an OAuth App to create or update workflow `.github/workflows/main.yml` without `workflow` scope)

### Steps to Reproduce
1. Modify GitHub workflow file in a non master branch
2. Push changes to repository

### Expected behavior
Visual Studio Github extensions has enough rights to create or update a workflow

### Logs
Error encountered while pushing to the remote repository: rejected features/cicd -> features/cicd (refusing to allow an OAuth App to create or update workflow `.github/workflows/main.yml` without `workflow` scope)

### Additional context
N/A

### PR DESCRIPTION
**Pull request by jcansdale**
This will allows users to update their GitHub actions workflow files.

Fixes #2455

### CODE REVIEW

**Comment by paolosalvatori** [comment]
I don't know if this feature has been implemented or not, but it doesn't work with Microsoft Visual Studio Enterprise 2019, Version 16.6.2. I tried to re-login to GitHub and nothing has changed. The workflow scope has not been acquired. This is a very annoying problem affecting both Visual Studio and Visual Studio Code.

**Comment by jcansdale** [comment]
Hi @paolosalvatori 👋 

Sorry about the delay getting back to you! I've just seen your message. 😊  Have you had any luck getting this to work since?

I'm wondering if your version of GitHub for VS has failed update. Could you check the extension manager and make sure you're on v2.11.104?

Thanks.

**Comment by jke94** [comment]
Hi @jcansdale!

Just thanks, half an hour looking for the problem 😊✌

Regards & thanks.

**Comment by jcansdale** [comment]
@jke94 I'm glad that helped! 🙂 

I'm guessing GitHub for Visual Studio auto-updates weren't working for you? 😢

**Pull request merged**
