### PR TITLE
Show proper message when repo is created

### LINKED ISSUE #54: Creating a repo on GitHub.com displays a notification that the repo was cloned successfully
Imported from https://github.com/github/VisualStudioInternal/issues/135

1. Launch VS
2. Team -> Manage Connections
3. Click on Create under the GitHub section
4. log in to GitHub.com on the login dialog
5. enter a repo name, description and local path
6. Click "Create Repository"

Actual: A notification that says "The repository was cloned successfully"
Expected: A more relevant notification that says my repo was created on GitHub.com.

### PR DESCRIPTION
**Pull request by shana**
Fixes #54

Also base this on the shana/list-git-repos branch so reviewing is saner.

### CODE REVIEW

**Comment by Haacked** [comment]
I'm going to close this and retarget it now that `shana/list-git-repos` is in `master`.

**Comment by Haacked** [comment]
Hmm, easier said than done. :stuck_out_tongue:

**Comment by shana** [comment]
Oh, yeah, things moved around a bit :smile: 
No worries, I'll fixicate ^_^

**Comment by Haacked** [comment]
> No worries, I'll fixicate ^_^

Heh heh. Thanks! I wanted to, but I got sidetracked.

**Pull request closed without merging**
