### PR TITLE
Show comment bubble when hovering over the current mouse line

### PR DESCRIPTION
**Pull request by shana**
Making commenting more discoverable by always showing the bubble when hovering over a line

### CODE REVIEW

**Comment by shana** [comment]
@jcansdale Been testing this one out and it works great. I agree that we should only do it on the diff view and not on the editor view.

**Comment by jcansdale** [comment]
@shana I've updated it so that it only tracks the mouse on the diff views.

**Comment by ungb** [comment]
One minor thing I found is if you hover between the line number and the comment gutter the comment icon doesn't show up.

image

**Comment by jcansdale** [comment]
@ungb Thanks for the catch! Could you try again with the latest push?

**Pull request merged**
