### PR TITLE
Fix icon color switch on theme change

### LINKED ISSUE #110: Invitation Card: Octocat logo is black on dark gray on the Visual Studio dark theme
After installing the GitHub extension on a new machine, the invitation card shows the logo in black on a very dark background. (This used to invert to white and should have continued to do so.) 

black_on_black

### PR DESCRIPTION
**Pull request by shana**
Fixes #110

### CODE REVIEW

**Comment by Haacked** [comment]
This does fix #110 in that the dark theme looks good. But now the light theme is too light!

**Comment by shana** [comment]
Darn it! It switched colors just fine for me when I tested it! Why the heck is it not refreshing?? *grumble*

**Comment by Haacked** [comment]
It switched colors just fine. I even switched to dark and back to light. It was still that faded color. Weird.

**Comment by shana** [comment]
What non-dark theme did you try? Light or Blue? I might only have tested with the Blue one.

**Comment by Haacked** [comment]
I did "Light"

**Comment by shana** [comment]
@Haacked I can tell this is on the connect page (because of the text), and this PR doesn't touch the connect page at all (only the invitation area on the sync page and the navigation items on the home page). 

I can't reproduce this problem though. What color scheme did you start visual studio with, before switching to the light scheme? Or did this happen when it started up?

**Comment by Haacked** [comment]
> I can tell this is on the connect page (because of the text), and this PR doesn't touch the connect page at all (only the invitation area on the sync page and the navigation items on the home page).

Doh! My bad.

> I can't reproduce this problem though. What color scheme did you start visual studio with, before switching to the light scheme? Or did this happen when it started up?

And I can no longer repro it either. I tested everything and this change looks good!

**Pull request merged**
