### PR TITLE
Add support for creating VS installer builds in appveyor

### PR DESCRIPTION
**Pull request by shana**
DO NOT MERGE MASTER INTO THIS BRANCH

This branch is based off of the v2.5.5.3913 tag, to make it easier to do vs installer builds from it.

What it does:
- Add option to do VS installer builds to the build scripts
- If a branch is named releases/*-vsinstaller, create an extra package in CI for the vs installer
- Only run code analysis on builds that produce packages
- Build packages on non-PR builds when building for the vs installer
- Remove stale solution configurations

### CODE REVIEW

**Comment by Wphelp98737** [comment]
# first get the git diff of pseudo...base
pseudo_diff_base = diff(pseudo...base)

# check if you allow offsets (default False)
if yaml["codecov.allow_coverage_offsets"] is False
  if pseudo_diff_base.adjusts_tracked_lines(pseudo.report)
    exit "Missing report base"

# adjust the report with changes in pseudo_diff_base
approx_base_report = pseudo.report.adjust_forward(pseudo_diff_base)

# get the pull diff
pull_diff = diff(base...head)

use compare(approx_base_report...head.report) in pull comment/statuses/etc.

**Comment by Wphelp98737** [comment]
# first get the git diff of pseudo...base
pseudo_diff_base = diff(pseudo...base)

# check if you allow offsets (default False)
if yaml["codecov.allow_coverage_offsets"] is False
  if pseudo_diff_base.adjusts_tracked_lines(pseudo.report)
    exit "Missing report base"

# adjust the report with changes in pseudo_diff_base
approx_base_report = pseudo.report.adjust_forward(pseudo_diff_base)

# get the pull diff
pull_diff = diff(base...head)

use compare(approx_base_report...head.report) in pull comment/statuses/etc.

**Comment by Wphelp98737** [comment]
# first get the git diff of pseudo...base
pseudo_diff_base = diff(pseudo...base)

# check if you allow offsets (default False)
if yaml["codecov.allow_coverage_offsets"] is False
  if pseudo_diff_base.adjusts_tracked_lines(pseudo.report)
    exit "Missing report base"

# adjust the report with changes in pseudo_diff_base
approx_base_report = pseudo.report.adjust_forward(pseudo_diff_base)

# get the pull diff
pull_diff = diff(base...head)

use compare(approx_base_report...head.report) in pull comment/statuses/etc.

**Comment by jcansdale** [comment]
We're no longer using AppVeyor. 😄

**Pull request closed without merging**
