### PR TITLE
[WIP] Resource cleanup

### PR DESCRIPTION
**Pull request by StanleyGoldman**
While reviewing resources it seems to me that these resources are never used.

### CODE REVIEW

**Comment by jcansdale** [comment]
@StanleyGoldman The resources appear to be used here, but I wish they weren't!

https://github.com/github/VisualStudio/blob/72c146d0605489b38104729ebfdda1a0acb528da/src/GitHub.StartPage/StartPagePackage.cs#L22-L23

I don't see where they appear in the extension.  Thought it was an about page thing, but don't see the text there. 😕

**Comment by StanleyGoldman** [comment]
Geez okay, i'm glad you found that.

**Comment by StanleyGoldman** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.providecodecontainerproviderattribute?view=visualstudiosdk-2017

**Comment by StanleyGoldman** [comment]
I have no idea what that attribute is for.

**Comment by StanleyGoldman** [comment]
We actually have to figure out how to translate these strings...

**Pull request closed without merging**
