### PR TITLE
Update GraphQL schema and add CheckConclusionState.(Skipped / Stale)

### LINKED ISSUE #2472: Could not convert 'STALE' to CheckConclusionState
This happens when viewing the PR list for:
https://github.com/AvaloniaUI/Avalonia

image

### PR DESCRIPTION
**Pull request by jcansdale**
The PR list was failing because new check conclusion states have been added. This updates the GraphQL schema and adds these new states.

### What this PR does

- Update to the latest GraphQL schema
- Fix `FromGraphQl ` so that knows about `CheckConclusionState` `Skipped` and `Stale` 
- Add extra `null` arguments to `MentionableUsers` and `Comments `

### How to test

- Check PR list is showing correctly for https://github.com/AvaloniaUI/Avalonia

### Questions

Which of the `Avalonia` PRs was using the new state and what does it look like now?

Fixes #2472

### CODE REVIEW

**Comment by Sanaz** [comment]
I have updated the extension to the latest version and still get the same error (https://github.com/github/VisualStudio/issues/2472). Any ideas @jcansdale?

**Comment by jcansdale** [comment]
@Sanaz,

This fix hasn't been deployed to the VS Marketplace yet. Could you try installing a recent .vsix 
artifact from master, e.g.:
https://github.com/github/VisualStudio/runs/513754957

Please let me know how you get on! 😄

**Comment by parto** [comment]
@jcansdale thanks. this fixes the issue.

**Comment by parto** [comment]
@jcansdale it has another problem though when trying to open a PR: 
Screen Shot 2020-03-17 at 12 59 52 PM

**Pull request merged**
