### PR TITLE
Fix build instructions

### PR DESCRIPTION
**Pull request by eogas**

### CODE REVIEW

**Comment by eogas** [comment]
Or should the .gitmodules file use the public URL for this repo?

**Comment by shana** [comment]
@eogas Ooops, apologies about breaking the public builds, the repo was private for a bit there. Yes, it should definitely use the public URL.

**Comment by eogas** [comment]
Cool, sorry for the bad PR.  I figured it was one or the other, but I'm not really familiar with the whole git modules thing.

**Comment by shana** [comment]
@eogas No worries, it was a useful PR! We would have missed the problem otherwise. It's fixed in master now, so you should be able to update the submodules now.

**Comment by eogas** [comment]
Sounds good.  Thanks!

**Pull request closed without merging**
