### PR TITLE
Enable spell checking where appropriate

### LINKED ISSUE #1617: Enable spell checking where appropriate
E.g. when creating a PR or adding a comment. It's simplly a case of `SpellCheck.IsEnabled="true"`` on `TextBox` controls!

image

This makes it appear more like on dotcom:
image

### PR DESCRIPTION
**Pull request by jcansdale**
### What this PR does

- Enable spell checking for inline comments
- Enable spell checking when publishing a repository
- Enable spell checking when summarizing a review
- Enable spell checking when creating a PR
- Enable spell checking when creating a repository
- Enable spell checking when creating a Gist
- Remove custom `DefaultContextMenu` so that spell-check context menu works

### Screenshots

The right-click context menu now appears to be working properly:
image

Leaving an inline comment:
image

Publishing a repository:
image

Summarizing a review:
image

Creating a PR:
image

Creating a repository:
image

Creating a Gist:
image

### To do 

- [x] Stop using `DefaultContextMenu` from:
https://github.com/github/VisualStudio/blob/9512481fbe22c33bad08b8f857852a2550b20bc2/src/GitHub.UI/Assets/Controls.xaml#L22
src/GitHub.UI/Assets/Controls.xaml:22
- [x] Enable spell check for creating a repository
- [x] Enable spell check for creating a gist

Fixes #1617

### CODE REVIEW

**Comment by meaghanlewis** [comment]
Hey @jcansdale this is looking good and working as expected! Spell check could also be enabled for things like creating a repository and creating a gist- was there a specific reason you didn't add spell check those scenarios?

**Comment by jcansdale** [comment]
>  Spell check could also be enabled for things like creating a repository and creating a gist- was there a specific reason you didn't add spell check those scenarios?

No, this was an oversight. Thanks for the catch!

**Comment by jcansdale** [comment]
@meaghanlewis I've now enabled spell checking when creating a repository or Gist. Also, the right-click context menu now shows suggestions (see image in description).

**Comment by meaghanlewis** [comment]
@jcansdale thanks for enabling spell checking for those additional scenarios! ✨ 

The only thing that I notice here is that the right-click context menu doesn't show when I'm leaving inline comments.

**Pull request merged**
